### ISSUE TITLE
implement defparser macro

### ISSUE THREAD

**Issue by judepayne** [babashka/instaparse-bb#4]
Hi, I was thinking about the defparser macro. Of course it couldn't possibly have worked inside the pod as it's defining a var in a different process :)
However, we should be able to implement it in instaparse-bb, perhaps starting with a simple version then moving to one which splits the work appropriately between compile time and runtime as instaparse itself does.

Possibly we could go further and have Parser as a record that implements Ifn (like instaparse) and so remove the limitation that parsers must be called with `parse`.
@borkdude you must have considered this when you implemented the instaparse pod and instaparse-bb, so it would be good to hear your thoughts.

**Comment by borkdude** [comment]
My thoughts: I just haven't thought deeply about it yet :)

**Comment by judepayne** [comment]
Lol. I'll investigate more deeply. Knock some code together as time permits. I think it's possible. You'd just have to port or re-implement most of the instaparse.core ns (which is not that big).

**Comment by judepayne** [comment]
Removing the limitation that parsers must be called with parse will be hard without support for implementing IFn on [records or types](https://github.com/babashka/sci/issues/808).

A simple `defparser` macro to get us closer to the instaparse interface is straightforward enough. I'll do a PR

**Comment by judepayne** [comment]
Closing.
instaparse-bb updated with:
- the `defparser` macro
- Parsers can be called directly like they're fns, as per Instaparse. Although currently in babashka, you can't have Records implement IFn, this can be worked around by using `reify` instead.
